// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: thunderdome.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email  string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Github string `protobuf:"bytes,2,opt,name=github,proto3" json:"github,omitempty"`
	Token  string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Credentials) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *Credentials) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credentials *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Status      string       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Accepted    bool         `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Verified    bool         `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *User) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type Ticket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DueDate     string   `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Repository  string   `protobuf:"bytes,6,opt,name=repository,proto3" json:"repository,omitempty"`
	User        string   `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Contacts    []string `protobuf:"bytes,8,rep,name=contacts,proto3" json:"contacts,omitempty"`
	BranchName  string   `protobuf:"bytes,9,opt,name=branch_name,json=branchName,proto3" json:"branch_name,omitempty"`
	PullRequest string   `protobuf:"bytes,10,opt,name=pull_request,json=pullRequest,proto3" json:"pull_request,omitempty"`
	HttpsUrl    string   `protobuf:"bytes,11,opt,name=https_url,json=httpsUrl,proto3" json:"https_url,omitempty"`
	SshUrl      string   `protobuf:"bytes,12,opt,name=ssh_url,json=sshUrl,proto3" json:"ssh_url,omitempty"`
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{2}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ticket) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ticket) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *Ticket) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Ticket) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Ticket) GetContacts() []string {
	if x != nil {
		return x.Contacts
	}
	return nil
}

func (x *Ticket) GetBranchName() string {
	if x != nil {
		return x.BranchName
	}
	return ""
}

func (x *Ticket) GetPullRequest() string {
	if x != nil {
		return x.PullRequest
	}
	return ""
}

func (x *Ticket) GetHttpsUrl() string {
	if x != nil {
		return x.HttpsUrl
	}
	return ""
}

func (x *Ticket) GetSshUrl() string {
	if x != nil {
		return x.SshUrl
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credentials *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetCredentials() *Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	User     *User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Ticket   *Ticket   `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetStatusResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetStatusResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type JoinUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *JoinUserRequest) Reset() {
	*x = JoinUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinUserRequest) ProtoMessage() {}

func (x *JoinUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinUserRequest.ProtoReflect.Descriptor instead.
func (*JoinUserRequest) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{7}
}

func (x *JoinUserRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type JoinUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	User     *User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *JoinUserResponse) Reset() {
	*x = JoinUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinUserResponse) ProtoMessage() {}

func (x *JoinUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinUserResponse.ProtoReflect.Descriptor instead.
func (*JoinUserResponse) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{8}
}

func (x *JoinUserResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *JoinUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LeaveUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *LeaveUserRequest) Reset() {
	*x = LeaveUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveUserRequest) ProtoMessage() {}

func (x *LeaveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveUserRequest.ProtoReflect.Descriptor instead.
func (*LeaveUserRequest) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveUserRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type LeaveUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *LeaveUserResponse) Reset() {
	*x = LeaveUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveUserResponse) ProtoMessage() {}

func (x *LeaveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveUserResponse.ProtoReflect.Descriptor instead.
func (*LeaveUserResponse) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{10}
}

func (x *LeaveUserResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type AcceptUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Accepted bool     `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *AcceptUserRequest) Reset() {
	*x = AcceptUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptUserRequest) ProtoMessage() {}

func (x *AcceptUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptUserRequest.ProtoReflect.Descriptor instead.
func (*AcceptUserRequest) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{11}
}

func (x *AcceptUserRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AcceptUserRequest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type AcceptUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *AcceptUserResponse) Reset() {
	*x = AcceptUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptUserResponse) ProtoMessage() {}

func (x *AcceptUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptUserResponse.ProtoReflect.Descriptor instead.
func (*AcceptUserResponse) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptUserResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type VerifyUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *VerifyUserRequest) Reset() {
	*x = VerifyUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserRequest) ProtoMessage() {}

func (x *VerifyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserRequest.ProtoReflect.Descriptor instead.
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyUserRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type VerifyUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *VerifyUserResponse) Reset() {
	*x = VerifyUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserResponse) ProtoMessage() {}

func (x *VerifyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserResponse.ProtoReflect.Descriptor instead.
func (*VerifyUserResponse) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyUserResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type ListTicketsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{15}
}

func (x *ListTicketsRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Tickets  []*Ticket `protobuf:"bytes,2,rep,name=tickets,proto3" json:"tickets,omitempty"`
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{16}
}

func (x *ListTicketsResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type ClaimTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Id      string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ClaimTicketRequest) Reset() {
	*x = ClaimTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTicketRequest) ProtoMessage() {}

func (x *ClaimTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTicketRequest.ProtoReflect.Descriptor instead.
func (*ClaimTicketRequest) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{17}
}

func (x *ClaimTicketRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ClaimTicketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ClaimTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Ticket   *Ticket   `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *ClaimTicketResponse) Reset() {
	*x = ClaimTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClaimTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTicketResponse) ProtoMessage() {}

func (x *ClaimTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTicketResponse.ProtoReflect.Descriptor instead.
func (*ClaimTicketResponse) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{18}
}

func (x *ClaimTicketResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ClaimTicketResponse) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type DropTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *DropTicketRequest) Reset() {
	*x = DropTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTicketRequest) ProtoMessage() {}

func (x *DropTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTicketRequest.ProtoReflect.Descriptor instead.
func (*DropTicketRequest) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{19}
}

func (x *DropTicketRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type DropTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DropTicketResponse) Reset() {
	*x = DropTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTicketResponse) ProtoMessage() {}

func (x *DropTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTicketResponse.ProtoReflect.Descriptor instead.
func (*DropTicketResponse) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{20}
}

func (x *DropTicketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GithubWebhookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GithubWebhookRequest) Reset() {
	*x = GithubWebhookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubWebhookRequest) ProtoMessage() {}

func (x *GithubWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubWebhookRequest.ProtoReflect.Descriptor instead.
func (*GithubWebhookRequest) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{21}
}

func (x *GithubWebhookRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type GithubWebhookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GithubWebhookResponse) Reset() {
	*x = GithubWebhookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thunderdome_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GithubWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GithubWebhookResponse) ProtoMessage() {}

func (x *GithubWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thunderdome_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GithubWebhookResponse.ProtoReflect.Descriptor instead.
func (*GithubWebhookResponse) Descriptor() ([]byte, []int) {
	return file_thunderdome_proto_rawDescGZIP(), []int{22}
}

func (x *GithubWebhookResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_thunderdome_proto protoreflect.FileDescriptor

var file_thunderdome_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x92, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0xb3, 0x02, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x75, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x75, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x75, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x74, 0x74, 0x70, 0x73, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x74, 0x74, 0x70, 0x73,
	0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x73, 0x68, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x73, 0x68, 0x55, 0x72, 0x6c, 0x22, 0x45, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74,
	0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x73, 0x22, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x42, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64,
	0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9a, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65,
	0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x22, 0x41, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64,
	0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74,
	0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x42, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x68, 0x75,
	0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x11, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x5f, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65,
	0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74,
	0x65, 0x64, 0x22, 0x47, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x68, 0x75,
	0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x11, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x47, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64,
	0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44, 0x0a, 0x12, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2e, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x77, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64,
	0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x68, 0x75,
	0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52,
	0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x54, 0x0a, 0x12, 0x43, 0x6c, 0x61, 0x69,
	0x6d, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x75,
	0x0a, 0x13, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65,
	0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64,
	0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x43, 0x0a, 0x11, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x68,
	0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x44, 0x72,
	0x6f, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x96, 0x06, 0x0a, 0x0b, 0x54, 0x68, 0x75, 0x6e,
	0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x12, 0x4c, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f,
	0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1c, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x4a, 0x6f,
	0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x09, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x2e,
	0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74,
	0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e,
	0x0a, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x74,
	0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74,
	0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0f, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x09, 0x12, 0x07, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x5e,
	0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x2e, 0x74,
	0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74,
	0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0f, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x09, 0x12, 0x07, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x52,
	0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x1f, 0x2e,
	0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x1f, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65,
	0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x1e, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f,
	0x6d, 0x65, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f,
	0x6d, 0x65, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x0d, 0x47, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x12, 0x21, 0x2e, 0x74, 0x68, 0x75, 0x6e, 0x64,
	0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62, 0x57, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x68,
	0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2e, 0x47, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x22, 0x07, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x68, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2d, 0x68, 0x71, 0x2f, 0x74, 0x68,
	0x75, 0x6e, 0x64, 0x65, 0x72, 0x64, 0x6f, 0x6d, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70,
	0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_thunderdome_proto_rawDescOnce sync.Once
	file_thunderdome_proto_rawDescData = file_thunderdome_proto_rawDesc
)

func file_thunderdome_proto_rawDescGZIP() []byte {
	file_thunderdome_proto_rawDescOnce.Do(func() {
		file_thunderdome_proto_rawDescData = protoimpl.X.CompressGZIP(file_thunderdome_proto_rawDescData)
	})
	return file_thunderdome_proto_rawDescData
}

var file_thunderdome_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_thunderdome_proto_goTypes = []interface{}{
	(*Credentials)(nil),           // 0: thunderdome.Credentials
	(*User)(nil),                  // 1: thunderdome.User
	(*Ticket)(nil),                // 2: thunderdome.Ticket
	(*Request)(nil),               // 3: thunderdome.Request
	(*Response)(nil),              // 4: thunderdome.Response
	(*GetStatusRequest)(nil),      // 5: thunderdome.GetStatusRequest
	(*GetStatusResponse)(nil),     // 6: thunderdome.GetStatusResponse
	(*JoinUserRequest)(nil),       // 7: thunderdome.JoinUserRequest
	(*JoinUserResponse)(nil),      // 8: thunderdome.JoinUserResponse
	(*LeaveUserRequest)(nil),      // 9: thunderdome.LeaveUserRequest
	(*LeaveUserResponse)(nil),     // 10: thunderdome.LeaveUserResponse
	(*AcceptUserRequest)(nil),     // 11: thunderdome.AcceptUserRequest
	(*AcceptUserResponse)(nil),    // 12: thunderdome.AcceptUserResponse
	(*VerifyUserRequest)(nil),     // 13: thunderdome.VerifyUserRequest
	(*VerifyUserResponse)(nil),    // 14: thunderdome.VerifyUserResponse
	(*ListTicketsRequest)(nil),    // 15: thunderdome.ListTicketsRequest
	(*ListTicketsResponse)(nil),   // 16: thunderdome.ListTicketsResponse
	(*ClaimTicketRequest)(nil),    // 17: thunderdome.ClaimTicketRequest
	(*ClaimTicketResponse)(nil),   // 18: thunderdome.ClaimTicketResponse
	(*DropTicketRequest)(nil),     // 19: thunderdome.DropTicketRequest
	(*DropTicketResponse)(nil),    // 20: thunderdome.DropTicketResponse
	(*GithubWebhookRequest)(nil),  // 21: thunderdome.GithubWebhookRequest
	(*GithubWebhookResponse)(nil), // 22: thunderdome.GithubWebhookResponse
}
var file_thunderdome_proto_depIdxs = []int32{
	0,  // 0: thunderdome.User.credentials:type_name -> thunderdome.Credentials
	0,  // 1: thunderdome.Request.credentials:type_name -> thunderdome.Credentials
	3,  // 2: thunderdome.GetStatusRequest.request:type_name -> thunderdome.Request
	4,  // 3: thunderdome.GetStatusResponse.response:type_name -> thunderdome.Response
	1,  // 4: thunderdome.GetStatusResponse.user:type_name -> thunderdome.User
	2,  // 5: thunderdome.GetStatusResponse.ticket:type_name -> thunderdome.Ticket
	3,  // 6: thunderdome.JoinUserRequest.request:type_name -> thunderdome.Request
	4,  // 7: thunderdome.JoinUserResponse.response:type_name -> thunderdome.Response
	1,  // 8: thunderdome.JoinUserResponse.user:type_name -> thunderdome.User
	3,  // 9: thunderdome.LeaveUserRequest.request:type_name -> thunderdome.Request
	4,  // 10: thunderdome.LeaveUserResponse.response:type_name -> thunderdome.Response
	3,  // 11: thunderdome.AcceptUserRequest.request:type_name -> thunderdome.Request
	4,  // 12: thunderdome.AcceptUserResponse.response:type_name -> thunderdome.Response
	3,  // 13: thunderdome.VerifyUserRequest.request:type_name -> thunderdome.Request
	4,  // 14: thunderdome.VerifyUserResponse.response:type_name -> thunderdome.Response
	3,  // 15: thunderdome.ListTicketsRequest.request:type_name -> thunderdome.Request
	4,  // 16: thunderdome.ListTicketsResponse.response:type_name -> thunderdome.Response
	2,  // 17: thunderdome.ListTicketsResponse.tickets:type_name -> thunderdome.Ticket
	3,  // 18: thunderdome.ClaimTicketRequest.request:type_name -> thunderdome.Request
	4,  // 19: thunderdome.ClaimTicketResponse.response:type_name -> thunderdome.Response
	2,  // 20: thunderdome.ClaimTicketResponse.ticket:type_name -> thunderdome.Ticket
	3,  // 21: thunderdome.DropTicketRequest.request:type_name -> thunderdome.Request
	5,  // 22: thunderdome.Thunderdome.GetStatus:input_type -> thunderdome.GetStatusRequest
	7,  // 23: thunderdome.Thunderdome.JoinUser:input_type -> thunderdome.JoinUserRequest
	9,  // 24: thunderdome.Thunderdome.LeaveUser:input_type -> thunderdome.LeaveUserRequest
	11, // 25: thunderdome.Thunderdome.AcceptUser:input_type -> thunderdome.AcceptUserRequest
	13, // 26: thunderdome.Thunderdome.VerifyUser:input_type -> thunderdome.VerifyUserRequest
	15, // 27: thunderdome.Thunderdome.ListTickets:input_type -> thunderdome.ListTicketsRequest
	17, // 28: thunderdome.Thunderdome.ClaimTicket:input_type -> thunderdome.ClaimTicketRequest
	19, // 29: thunderdome.Thunderdome.DropTicket:input_type -> thunderdome.DropTicketRequest
	21, // 30: thunderdome.Thunderdome.GithubWebhook:input_type -> thunderdome.GithubWebhookRequest
	6,  // 31: thunderdome.Thunderdome.GetStatus:output_type -> thunderdome.GetStatusResponse
	8,  // 32: thunderdome.Thunderdome.JoinUser:output_type -> thunderdome.JoinUserResponse
	10, // 33: thunderdome.Thunderdome.LeaveUser:output_type -> thunderdome.LeaveUserResponse
	12, // 34: thunderdome.Thunderdome.AcceptUser:output_type -> thunderdome.AcceptUserResponse
	14, // 35: thunderdome.Thunderdome.VerifyUser:output_type -> thunderdome.VerifyUserResponse
	16, // 36: thunderdome.Thunderdome.ListTickets:output_type -> thunderdome.ListTicketsResponse
	18, // 37: thunderdome.Thunderdome.ClaimTicket:output_type -> thunderdome.ClaimTicketResponse
	20, // 38: thunderdome.Thunderdome.DropTicket:output_type -> thunderdome.DropTicketResponse
	22, // 39: thunderdome.Thunderdome.GithubWebhook:output_type -> thunderdome.GithubWebhookResponse
	31, // [31:40] is the sub-list for method output_type
	22, // [22:31] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_thunderdome_proto_init() }
func file_thunderdome_proto_init() {
	if File_thunderdome_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_thunderdome_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTicketsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTicketsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClaimTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubWebhookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thunderdome_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GithubWebhookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thunderdome_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thunderdome_proto_goTypes,
		DependencyIndexes: file_thunderdome_proto_depIdxs,
		MessageInfos:      file_thunderdome_proto_msgTypes,
	}.Build()
	File_thunderdome_proto = out.File
	file_thunderdome_proto_rawDesc = nil
	file_thunderdome_proto_goTypes = nil
	file_thunderdome_proto_depIdxs = nil
}
